# Generated by Django 4.1.3 on 2022-11-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.IntegerField()),
                ('titleName', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
