# Generated by Django 4.1.3 on 2022-11-11 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_todolist_delete_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='sn',
        ),
    ]
